import { ICards } from './components/Icards';

const cards: [string[], ...ICards[][]] = [
// const cards = [
  ['animals', 'animals2', 'clothing', 'gastronomy', 'music', 'sport', 'toys', 'travel'],
  [
    {
      category: 'animals',
      word: 'Bear',
      translation: 'Медведь',
      audioSrc: 'audio/bear.mp3',
    },
    {
      category: 'animals',
      word: 'Deer',
      translation: 'Олень',
      audioSrc: 'audio/deer.mp3',
    },
    {
      category: 'animals',
      word: 'Duck',
      translation: 'Утка',
      audioSrc: 'duck.mp3',
    },
    {
      category: 'animals',
      word: 'Hedgehog',
      translation: 'Ежик',
      audioSrc: 'hedgehog.mp3',
    },
    {
      category: 'animals',
      word: 'Owl',
      translation: 'Сова',
      audioSrc: 'owl.mp3',
    },
    {
      category: 'animals',
      word: 'Rabbit',
      translation: 'Кролик',
      audioSrc: 'rabbit.mp3',
    },
    {
      category: 'animals',
      word: 'Raccoon',
      translation: 'Енот',
      audioSrc: 'raccoon.mp3',
    },
    {
      category: 'animals',
      word: 'Squirrel',
      translation: 'Белка',
      audioSrc: 'squirrel.mp3',
    },
  ],
  [
    {
      category: 'animals2',
      word: 'Cat',
      translation: 'Кот',
      audioSrc: 'cat.mp3',
    },
    {
      category: 'animals2',
      word: 'Duck',
      translation: 'Утка',
      audioSrc: 'duck.mp3',
    },
    {
      category: 'animals2',
      word: 'Elephant',
      translation: 'Слон',
      audioSrc: 'elephant.mp3',
    },
    {
      category: 'animals2',
      word: 'Fox',
      translation: 'Лиса',
      audioSrc: 'fox.mp3',
    },
    {
      category: 'animals2',
      word: 'Giraffe',
      translation: 'Жираф',
      audioSrc: 'giraffe.mp3',
    },
    {
      category: 'animals2',
      word: 'Lamb',
      translation: 'Ягненок',
      audioSrc: 'lamb.mp3',
    },
    {
      category: 'animals2',
      word: 'Lion',
      translation: 'Лев',
      audioSrc: 'lion.mp3',
    },
    {
      category: 'animals2',
      word: 'Panda',
      translation: 'Панда',
      audioSrc: 'panda.mp3',
    },
  ],
  [
    {
      category: 'clothing',
      word: 'Bag',
      translation: 'Сумка',
      audioSrc: 'bag.mp3',
    },
    {
      category: 'clothing',
      word: 'Dress',
      translation: 'Платье',
      audioSrc: 'dress.mp3',
    },
    {
      category: 'clothing',
      word: 'Hat',
      translation: 'Шляпа',
      audioSrc: 'hat.mp3',
    },
    {
      category: 'clothing',
      word: 'Jacket',
      translation: 'Куртка',
      audioSrc: 'jacket.mp3',
    },
    {
      category: 'clothing',
      word: 'Shoes',
      translation: 'Туфли',
      audioSrc: 'shoes.mp3',
    },
    {
      category: 'clothing',
      word: 'Shorts',
      translation: 'Шорты',
      audioSrc: 'shorts.mp3',
    },
    {
      category: 'clothing',
      word: 'Skirt',
      translation: 'Юбка',
      audioSrc: 'skirt.mp3',
    },
    {
      category: 'clothing',
      word: 'T-shirt',
      translation: 'Футболка',
      audioSrc: 't-shirt.mp3',
    },
  ],
  [
    {
      category: 'gastronomy',
      word: 'Apple',
      translation: 'Яблоко',
      audioSrc: 'apple.mp3',
    },
    {
      category: 'gastronomy',
      word: 'Carrot',
      translation: 'Морковь',
      audioSrc: 'carrot.mp3',
    },
    {
      category: 'gastronomy',
      word: 'Banana',
      translation: 'Банан',
      audioSrc: 'banana.mp3',
    },
    {
      category: 'gastronomy',
      word: 'Egg',
      translation: 'Яйцо',
      audioSrc: 'egg.mp3',
    },
    {
      category: 'gastronomy',
      word: 'Cheese',
      translation: 'Сыр',
      audioSrc: 'cheese.mp3',
    },
    {
      category: 'gastronomy',
      word: 'Mandarin',
      translation: 'Мандарин',
      audioSrc: 'mandarin.mp3',
    },
    {
      category: 'gastronomy',
      word: 'Pie',
      translation: 'Пирог',
      audioSrc: 'pie.mp3',
    },
    {
      category: 'gastronomy',
      word: 'Pumpkin',
      translation: 'Тыква',
      audioSrc: 'pumpkin.mp3',
    },
  ],
  [
    {
      category: 'music',
      word: 'Accordion',
      translation: 'Аккордеон',
      audioSrc: 'accordion.mp3',
    },
    {
      category: 'music',
      word: 'Drum',
      translation: 'Барабан',
      audioSrc: 'drum.mp3',
    },
    {
      category: 'music',
      word: 'Flute',
      translation: 'Флейта',
      audioSrc: 'flute.mp3',
    },
    {
      category: 'music',
      word: 'Metronome',
      translation: 'Метроном',
      audioSrc: 'metronome.mp3',
    },
    {
      category: 'music',
      word: 'Microphone',
      translation: 'Микрофон',
      audioSrc: 'microphone.mp3',
    },
    {
      category: 'music',
      word: 'Piano',
      translation: 'Пианино',
      audioSrc: 'piano.mp3',
    },
    {
      category: 'music',
      word: 'Saxophone',
      translation: 'Саксофон',
      audioSrc: 'saxophone.mp3',
    },
    {
      category: 'music',
      word: 'Violin',
      translation: 'Скрипка',
      audioSrc: 'violin.mp3',
    },
  ],
  [
    {
      category: 'sport',
      word: 'Badminton',
      translation: 'Бадминтон',
      audioSrc: 'badminton.mp3',
    },
    {
      category: 'sport',
      word: 'Bicycle',
      translation: 'Велосипед',
      audioSrc: 'bicycle.mp3',
    },
    {
      category: 'sport',
      word: 'Cricket',
      translation: 'Крикет',
      audioSrc: 'cricket.mp3',
    },
    {
      category: 'sport',
      word: 'Football',
      translation: 'Футбол',
      audioSrc: 'football.mp3',
    },
    {
      category: 'sport',
      word: 'Kayak',
      translation: 'Каяк',
      audioSrc: 'kayak.mp3',
    },
    {
      category: 'sport',
      word: 'Pool',
      translation: 'Бильярд',
      audioSrc: 'pool.mp3',
    },
    {
      category: 'sport',
      word: 'Rings',
      translation: 'Кольца',
      audioSrc: 'rings.mp3',
    },
    {
      category: 'sport',
      word: 'Gymnastics',
      translation: 'Гимнастика',
      audioSrc: 'gymnastics.mp3',
    },
  ],
  [
    {
      category: 'toys',
      word: 'Boat',
      translation: 'Лодка',
      audioSrc: 'boat.mp3',
    },
    {
      category: 'toys',
      word: 'Car',
      translation: 'Машина',
      audioSrc: 'car.mp3',
    },
    {
      category: 'toys',
      word: 'Doll',
      translation: 'Кукла',
      audioSrc: 'doll.mp3',
    },
    {
      category: 'toys',
      word: 'Airplane',
      translation: 'Самолет',
      audioSrc: 'airplane.mp3',
    },
    {
      category: 'toys',
      word: 'Dinosaur',
      translation: 'Динозавр',
      audioSrc: 'dinosaur.mp3',
    },
    {
      category: 'toys',
      word: 'Horse',
      translation: 'Лошадь',
      audioSrc: 'horse.mp3',
    },
    {
      category: 'toys',
      word: 'Robot',
      translation: 'Робот',
      audioSrc: 'robot.mp3',
    },
    {
      category: 'toys',
      word: 'Train',
      translation: 'Поезд',
      audioSrc: 'train.mp3',
    },
  ],
  [
    {
      category: 'travel',
      word: 'Backpack',
      translation: 'Рюкзак',
      audioSrc: 'backpack.mp3',
    },
    {
      category: 'travel',
      word: 'Campfire',
      translation: 'Походный костер',
      audioSrc: 'campfire.mp3',
    },
    {
      category: 'travel',
      word: 'Compass',
      translation: 'Компас',
      audioSrc: 'compass.mp3',
    },
    {
      category: 'travel',
      word: 'Globe',
      translation: 'Глобус',
      audioSrc: 'globe.mp3',
    },
    {
      category: 'travel',
      word: 'Map',
      translation: 'Карта',
      audioSrc: 'map.mp3',
    },
    {
      category: 'travel',
      word: 'Knife',
      translation: 'Нож',
      audioSrc: 'knife.mp3',
    },
    {
      category: 'travel',
      word: 'Suitcase',
      translation: 'Чемодан',
      audioSrc: 'suitcase.mp3',
    },
    {
      category: 'travel',
      word: 'Tent',
      translation: 'Палатка',
      audioSrc: 'tent.mp3',
    },
  ],
];

export default cards;
